phrase:
  project_id: 68b322b313e8e7b729bb377fd5886db7
  
  push:
    sources:
    - file: locale/fr.json
      params:
        update_translations: true 
        
  pull:
    targets:
    - file: "locale/en.json"
      params:
        include_unverified_translations: true
