phrase:
  project_id: 68b322b313e8e7b729bb377fd5886db7
  
  push:
    sources:
    - file: locale/fr.json
      params:
        file_format: simple_json
        update_translations: true
        locale_id: 20b6dc6960699d169f2633c1be5bdd75
        
  pull:
    targets:
    - file: "locale/en.json"
      params:
        file_format: simple_json
        include_unverified_translations: true
        locale_id: 630f283e75c063fbdd080e8b027a450c
